In [2]:
import torch
import torchvision.transforms as transforms
from PIL import Image


ModuleNotFoundError: No module named 'torchvision'

In [ ]:
A = torch.randn(3, 3)
B = torch.zeros(3, 3) + 3  
sum_tensor = A + B
mul_tensor = A * B
A_T = A.t()

print("1-тапсырма: Тензорлармен негізгі амалдар")
print("A:", A)
print("B:", B)
print("Қосу:", sum_tensor)
print("Көбейту:", mul_tensor)
print("A транспозициясы:", A_T)

1-тапсырма: Тензорлармен негізгі амалдар
A: tensor([[ 2.2934,  0.4189,  0.1409],
        [ 0.5363,  0.6760,  1.0737],
        [-0.3211,  0.7256, -1.2581]])
B: tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
Қосу: tensor([[5.2934, 3.4189, 3.1409],
        [3.5363, 3.6760, 4.0737],
        [2.6789, 3.7256, 1.7419]])
Көбейту: tensor([[ 6.8801,  1.2568,  0.4226],
        [ 1.6089,  2.0281,  3.2210],
        [-0.9633,  2.1769, -3.7742]])
A транспозициясы: tensor([[ 2.2934,  0.5363, -0.3211],
        [ 0.4189,  0.6760,  0.7256],
        [ 0.1409,  1.0737, -1.2581]])


In [11]:
X = torch.arange(1, 17).reshape(4, 4)
X_diag_six = X.clone()
X_diag_six.fill_diagonal_(6)

X_diag_six[0, :] = torch.arange(1, 5)
X_diag_six[:, 1] *= 2

X_even_zero = X_diag_six.clone()
X_even_zero[X_even_zero % 2 == 0] = 0

print("Бастапқы X:\n", X)
print("Диагоналі 6-ға ауыстырылған X:\n", X_diag_six)
print("Жұп сандары 0-ге ауыстырылған X:\n", X_even_zero)


Бастапқы X:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
Диагоналі 6-ға ауыстырылған X:
 tensor([[ 1,  4,  3,  4],
        [ 5, 12,  7,  8],
        [ 9, 20,  6, 12],
        [13, 28, 15,  6]])
Жұп сандары 0-ге ауыстырылған X:
 tensor([[ 1,  0,  3,  0],
        [ 5,  0,  7,  0],
        [ 9,  0,  0,  0],
        [13,  0, 15,  0]])


In [16]:

transform = transforms.ToTensor()
image1 = transform(Image.open("gift.jpg"))
image2 = transform(Image.open("bw.jpg"))
image1 = transforms.CenterCrop((2, 3))(image1)
image2 = transforms.CenterCrop((2, 3))(image2)

image1 = image1.squeeze(0)  
image2 = image2.squeeze(0)

sum_images = image1 + image2

mul_images = image1 * image2

dot_product = torch.matmul(image1.flatten(), image2.flatten())

image1_T = image1.T 

square_matrix = image1[:, :2] 

if square_matrix.shape[0] == square_matrix.shape[1]:  
    det_A = torch.linalg.det(square_matrix)  
else:
    det_A = "Анықтауыш тек квадрат матрица үшін есептеледі"

last_column = image2[:, -1] 
norm_last_column = torch.linalg.norm(last_column)  

print("Қосынды:\n", sum_images)
print("Элемент бойынша көбейту:\n", mul_images)
print("Скаляр көбейтіндісі:\n", dot_product)
print("Транспозиция:\n", image1_T)
print("Анықтауыш:\n", det_A)
print("Соңғы баған:\n", last_column)
print("Соңғы бағанның нормасы:\n", norm_last_column)


Қосынды:
 tensor([[[1.1059, 0.8000, 0.8196],
         [0.8275, 0.7451, 0.7451]],

        [[1.0314, 0.7451, 0.7922],
         [0.7804, 0.7216, 0.7373]],

        [[0.9137, 0.6431, 0.7176],
         [0.6784, 0.6353, 0.6784]]])
Элемент бойынша көбейту:
 tensor([[[0.2996, 0.1231, 0.1375],
         [0.1304, 0.0923, 0.0972]],

        [[0.2525, 0.0906, 0.1214],
         [0.1014, 0.0784, 0.0927]],

        [[0.1783, 0.0302, 0.0779],
         [0.0386, 0.0277, 0.0588]]])
Скаляр көбейтіндісі:
 tensor(2.0286)
Транспозиция:
 tensor([[[0.4745, 0.4000, 0.2824],
         [0.2118, 0.1647, 0.0627]],

        [[0.2078, 0.1529, 0.0510],
         [0.1569, 0.1333, 0.0471]],

        [[0.2353, 0.2078, 0.1333],
         [0.1686, 0.1608, 0.1020]]])
Анықтауыш:
 Анықтауыш тек квадрат матрица үшін есептеледі
Соңғы баған:
 tensor([[0.6157, 0.5882, 0.5765],
        [0.6157, 0.5882, 0.5765],
        [0.6157, 0.5882, 0.5765]])
Соңғы бағанның нормасы:
 tensor(1.7811)


In [15]:
image = cv2.imread("img.jpg", cv2.IMREAD_GRAYSCALE)
print(image.shape)
image = cv2.resize(image, (32, 32)) 
image_tensor = torch.from_numpy(image).float()  
print(image_tensor.shape)
B = torch.randn(32, 32)  

sum_tensor = image_tensor + B  
elementwise_mul = image_tensor * B 
matmul_tensor = torch.matmul(image_tensor, B.T)  

image_reshaped = image_tensor.view(16, 64)

fig, axes = plt.subplots(1, 5, figsize=(25, 5))

print(image_reshaped.shape)

axes[0].imshow(image_tensor.numpy(), cmap="gray", aspect='auto')
axes[0].set_title("Бастапқы сурет ")

axes[1].imshow(sum_tensor.numpy(), cmap="gray", aspect='auto')
axes[1].set_title("A + B (Қосынды)")

axes[2].imshow(elementwise_mul.numpy(), cmap="gray", aspect='auto')
axes[2].set_title("Элементтік көбейту")

axes[3].imshow(image_reshaped.numpy(), cmap="gray", aspect='auto')
axes[3].set_title("Қайта пішімделген тензор")

axes[4].imshow(matmul_tensor.numpy(), cmap="gray", aspect='auto')
axes[4].set_title("Матрицалық көбейту (MatMul)")


plt.show()


NameError: name 'cv2' is not defined